# Generated by Django 3.0 on 2020-03-18 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='secret_pin',
            field=models.IntegerField(default=12345678),
            preserve_default=False,
        ),
    ]
