# Generated by Django 3.0 on 2020-03-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_userprofile_secret_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('Parent', 'Parent'), ('Student', 'Student'), ('Teacher', 'Teacher'), ('Admin', 'Admin'), ('Accountant', 'Accountant'), ('Liberian', 'Liberian')], default='Student', max_length=100),
            preserve_default=False,
        ),
    ]
