# Generated by Django 3.0 on 2020-04-04 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_remove_unusedpins_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.TextField(default='lagos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='birthday',
            field=models.CharField(default='22/02/2001', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='class_room',
            field=models.CharField(default='jss2', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(default='Male', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='now.jpg', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.TextField(default='ochuko'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='parent',
            field=models.CharField(default='Adeolu Adebowale', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(default='09013726303', max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='school_type',
            field=models.CharField(default='Day School', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='section',
            field=models.CharField(default='2017/2018', max_length=100),
            preserve_default=False,
        ),
    ]
