# Generated by Django 3.0 on 2020-04-07 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_auto_20200404_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birthday',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
