# Generated by Django 3.0 on 2020-04-07 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_userprofile_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='session',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
