# Generated by Django 3.0 on 2020-04-08 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_auto_20200407_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulkstudent',
            name='class_room',
        ),
        migrations.RemoveField(
            model_name='bulkstudent',
            name='session',
        ),
    ]
