# Generated by Django 3.0 on 2020-04-10 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_attend'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attend',
            new_name='AttendClass',
        ),
    ]
