# Generated by Django 3.0 on 2020-04-21 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0017_attendclass_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendclass',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
