# Generated by Django 3.0 on 2020-04-22 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0018_auto_20200421_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
