# Generated by Django 3.0 on 2020-04-23 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0023_auto_20200424_0130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facereg',
            name='creator',
        ),
    ]
