# Generated by Django 3.0 on 2020-04-24 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0025_facereg_creator'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FaceReg',
        ),
    ]
