# Generated by Django 2.2.4 on 2020-10-31 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0026_delete_facereg'),
    ]

    operations = [
        migrations.CreateModel(
            name='qr_test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
